In [1]:
import pandas as pd
import numpy as np

In [2]:
#import column info
df_gender_age_info = pd.read_csv("gender_age_metadata.csv", index_col=0) 
df_gender_age_info

                                                            id
GEO_ID
NAME                                      Geographic Area Name
DP05_0001E             Estimate!!SEX AND AGE!!Total population
DP05_0001M      Margin of Error!!SEX AND AGE!!Total population
DP05_0001PE             Percent!!SEX AND AGE!!Total population
DP05_0001PM  Percent Margin of Error!!SEX AND AGE!!Total po...
...                                                        ...
DP05_0088PM  Percent Margin of Error!!CITIZEN, VOTING AGE P...
DP05_0089E   Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...
DP05_0089M   Margin of Error!!CITIZEN, VOTING AGE POPULATIO...
DP05_0089PE  Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...
DP05_0089PM  Percent Margin of Error!!CITIZEN, VOTING AGE P...

[357 rows x 1 columns]

In [3]:
#create filter for desired columns
gender_age_info_rows = ["DP05_0001E", "DP05_0003E", "DP05_0004E", "DP05_0009E", "DP05_0010E", "DP05_0011E", "DP05_0012E", "DP05_0013E", "DP05_0014E"]

In [4]:
#filter for desired columns
df_gender_age_info = df_gender_age_info.loc[gender_age_info_rows] 
df_gender_age_info

                                                           id
GEO_ID
DP05_0001E            Estimate!!SEX AND AGE!!Total population
DP05_0003E    Estimate!!SEX AND AGE!!Total population!!Female
DP05_0004E  Estimate!!SEX AND AGE!!Total population!!Sex r...
DP05_0009E  Estimate!!SEX AND AGE!!Total population!!20 to...
DP05_0010E  Estimate!!SEX AND AGE!!Total population!!25 to...
DP05_0011E  Estimate!!SEX AND AGE!!Total population!!35 to...
DP05_0012E  Estimate!!SEX AND AGE!!Total population!!45 to...
DP05_0013E  Estimate!!SEX AND AGE!!Total population!!55 to...
DP05_0014E  Estimate!!SEX AND AGE!!Total population!!60 to...

In [5]:
#clean column names
df_gender_age_info['id'] = df_gender_age_info.id.map(lambda x: x.lstrip("Estimate!!SEX AND AGE!!"))
df_gender_age_info['id'] = df_gender_age_info.id.replace("!!", ": ", regex=True)
df_gender_age_info

                                                           id
GEO_ID
DP05_0001E                                   Total population
DP05_0003E                           Total population: Female
DP05_0004E  Total population: Sex ratio (males per 100 fem...
DP05_0009E                   Total population: 20 to 24 years
DP05_0010E                   Total population: 25 to 34 years
DP05_0011E                   Total population: 35 to 44 years
DP05_0012E                   Total population: 45 to 54 years
DP05_0013E                   Total population: 55 to 59 years
DP05_0014E                   Total population: 60 to 64 years

In [6]:
df_gender_age = pd.read_csv("gender_age_data_with_overlays.csv", index_col = 0)
df_gender_age

,NAME,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,...,DP05_0087PE,DP05_0087PM,DP05_0088E,DP05_0088M,DP05_0088PE,DP05_0088PM,DP05_0089E,DP05_0089M,DP05_0089PE,DP05_0089PM
GEO_ID,,,,,,,,,,,,,,,,,,,,,
id,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Percent!!SEX AND AGE!!Total population,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Percent!!SEX AND AGE!!Total population!!Male,Percent Margin of Error!!SEX AND AGE!!Total po...,Estimate!!SEX AND AGE!!Total population!!Female,...,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...","Margin of Error!!CITIZEN, VOTING AGE POPULATIO...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Estimate!!CITIZEN, VOTING AGE POPULATION!!Citi...","Margin of Error!!CITIZEN, VOTING AGE POPULATIO...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P..."
1400000US36061000100,"Census Tract 1, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**
1400000US36061000201,"Census Tract 2.01, New York County, New York",2750,226,2750,(X),1167,176,42.4,4.5,1583,...,1687,(X),596,158,35.3,6.2,1091,152,64.7,6.2
1400000US36061000202,"Census Tract 2.02, New York County, New York",7773,831,7773,(X),3400,519,43.7,4.3,4373,...,5775,(X),2537,466,43.9,5.3,3238,432,56.1,5.3
1400000US36061000500,"Census Tract 5, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400000US36061030900,"Census Tract 309, New York County, New York",10593,921,10593,(X),4769,720,45.0,4.5,5824,...,6132,(X),2486,468,40.5,5.7,3646,399,59.5,5.7
1400000US36061031100,"Census Tract 311, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**
1400000US36061031703,"Census Tract 317.03, New York County, New York",5783,469,5783,(X),2893,331,50.0,4.5,2890,...,3022,(X),1481,216,49.0,5.0,1541,237,51.0,5.0
1400000US36061031704,"Census Tract 317.04, New York County, New York",10224,937,10224,(X),5268,620,51.5,3.3,4956,...,6778,(X),3497,475,51.6,3.7,3281,413,48.4,3.7
1400000US36061031900,"Census Tract 319, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**

In [7]:
df_gender_age = df_gender_age.iloc[1:] 
df_gender_age

,NAME,DP05_0001E,DP05_0001M,DP05_0001PE,DP05_0001PM,DP05_0002E,DP05_0002M,DP05_0002PE,DP05_0002PM,DP05_0003E,...,DP05_0087PE,DP05_0087PM,DP05_0088E,DP05_0088M,DP05_0088PE,DP05_0088PM,DP05_0089E,DP05_0089M,DP05_0089PE,DP05_0089PM
GEO_ID,,,,,,,,,,,,,,,,,,,,,
1400000US36061000100,"Census Tract 1, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**
1400000US36061000201,"Census Tract 2.01, New York County, New York",2750,226,2750,(X),1167,176,42.4,4.5,1583,...,1687,(X),596,158,35.3,6.2,1091,152,64.7,6.2
1400000US36061000202,"Census Tract 2.02, New York County, New York",7773,831,7773,(X),3400,519,43.7,4.3,4373,...,5775,(X),2537,466,43.9,5.3,3238,432,56.1,5.3
1400000US36061000500,"Census Tract 5, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**
1400000US36061000600,"Census Tract 6, New York County, New York",9838,1024,9838,(X),4593,646,46.7,3.4,5245,...,6928,(X),3241,593,46.8,4.7,3687,425,53.2,4.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400000US36061030900,"Census Tract 309, New York County, New York",10593,921,10593,(X),4769,720,45.0,4.5,5824,...,6132,(X),2486,468,40.5,5.7,3646,399,59.5,5.7
1400000US36061031100,"Census Tract 311, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**
1400000US36061031703,"Census Tract 317.03, New York County, New York",5783,469,5783,(X),2893,331,50.0,4.5,2890,...,3022,(X),1481,216,49.0,5.0,1541,237,51.0,5.0
1400000US36061031704,"Census Tract 317.04, New York County, New York",10224,937,10224,(X),5268,620,51.5,3.3,4956,...,6778,(X),3497,475,51.6,3.7,3281,413,48.4,3.7
1400000US36061031900,"Census Tract 319, New York County, New York",0,12,0,(X),0,12,-,**,0,...,0,(X),0,12,-,**,0,12,-,**